/*
 * base.h
 *
 *  Created on: Sep 25, 2026
 *      Author: Admin
 */

#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE  (0x40000000)

#define APB1_PERIPHERAL_OFFSET (0x00000)
#define APB1_PERIPHERAL			(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET (0x00010000)
#define APB2_PERIPHERAL			(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB1_PERIPHERAL_OFFSET (0x00020000)
#define AHB1_PERIPHERAL			(PERIPHERAL_BASE + AHB1_PERIPHERAL_OFFSET)

#define AHB2_PERIPHERAL_OFFSET (0x1000 0000)
#define AHB2_PERIPHERAL			(PERIPHERAL_BASE + AHB2_PERIPHERAL_OFFSET)

#define GPIOA_PERIPHERAL_OFFSET (0x00020000)
#define GPIOA_PERIPHERAL 		(PERIPHERAL_BASE + GPIOA_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET (0x00020400)
#define GPIOB_PERIPHERAL 		(PERIPHERAL_BASE + GPIOB_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET (0x00020800)
#define GPIOC_PERIPHERAL 		(PERIPHERAL_BASE + GPIOC_PERIPHERAL_OFFSET)

#define GPIOD_PERIPHERAL_OFFSET (0x00020C00)
#define GPIOD_PERIPHERAL 		(PERIPHERAL_BASE + GPIOD_PERIPHERAL_OFFSET)

#define GPIOE_PERIPHERAL_OFFSET (0x00021000)
#define GPIOE_PERIPHERAL 		(PERIPHERAL_BASE + GPIOE_PERIPHERAL_OFFSET)

#define GPIOF_PERIPHERAL_OFFSET (0x00021400 )
#define GPIOF_PERIPHERAL 		(PERIPHERAL_BASE + GPIOF_PERIPHERAL_OFFSET)

#define GPIOG_PERIPHERAL_OFFSET (0x00021800)
#define GPIOG_PERIPHERAL 		(PERIPHERAL_BASE + GPIOG_PERIPHERAL_OFFSET)

#define GPIOH_PERIPHERAL_OFFSET (0x00021C00)
#define GPIOH_PERIPHERAL 		(PERIPHERAL_BASE + GPIOH_PERIPHERAL_OFFSET)

#define RCC_OFFSET 				(0x00023800 )
#define RCC_PERIPHERAL			(PERIPHERAL_BASE + RCC_OFFSET)

#define USART1_OFFSET			(0x00001000)
#define USART1_PERIPHERAL		(APB2_PERIPHERAL + USART1_OFFSET)

#define USART2_OFFSET			(0x00004400)
#define USART2_PERIPHERAL		(APB1_PERIPHERAL + USART2_OFFSET)

#define USART3_OFFSET			(0x00004800)
#define USART3_PERIPHERAL		(APB1_PERIPHERAL + USART3_OFFSET)

#define USART4_OFFSET			(0x00004C00)
#define USART4_PERIPHERAL		(APB1_PERIPHERAL + USART4_OFFSET)

#define USART5_OFFSET			(0x00005000)
#define USART5_PERIPHERAL		(APB1_PERIPHERAL + USART5_OFFSET)

#define USART6_OFFSET			(0x00001400 )
#define USART6_PERIPHERAL		(APB2_PERIPHERAL + USART6_OFFSET)

#define ADC_OFFSET				(0x00002000 )
#define ADC_PERIPHERAL			(APB2_PERIPHERAL + ADC_OFFSET)

#define ADC1_OFFSET				(0x000)
#define ADC1_PERIPHERAL			(ADC_PERIPHERAL + ADC1_OFFSET)

#define ADC2_OFFSET				(0x100)
#define ADC2_PERIPHERAL			(ADC_PERIPHERAL + ADC2_OFFSET)

#define ADC3_OFFSET				(0x200)
#define ADC3_PERIPHERAL			(ADC_PERIPHERAL + ADC3_OFFSET)

#endif /* BASE_H_ */
